// Generated by gencpp from file potentiometer/encoder.msg
// DO NOT EDIT!


#ifndef POTENTIOMETER_MESSAGE_ENCODER_H
#define POTENTIOMETER_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace potentiometer
{
template <class ContainerAllocator>
struct encoder_
{
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
    : desired(0)
    , actual(0)  {
    }
  encoder_(const ContainerAllocator& _alloc)
    : desired(0)
    , actual(0)  {
  (void)_alloc;
    }



   typedef int32_t _desired_type;
  _desired_type desired;

   typedef int32_t _actual_type;
  _actual_type actual;





  typedef boost::shared_ptr< ::potentiometer::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::potentiometer::encoder_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_

typedef ::potentiometer::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::potentiometer::encoder > encoderPtr;
typedef boost::shared_ptr< ::potentiometer::encoder const> encoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::potentiometer::encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::potentiometer::encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace potentiometer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'potentiometer': ['/home/pi/winch_ws/src/potentiometer/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::potentiometer::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::potentiometer::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potentiometer::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potentiometer::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potentiometer::encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potentiometer::encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::potentiometer::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "228bf8fb168564ebccf3e320dc392525";
  }

  static const char* value(const ::potentiometer::encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x228bf8fb168564ebULL;
  static const uint64_t static_value2 = 0xccf3e320dc392525ULL;
};

template<class ContainerAllocator>
struct DataType< ::potentiometer::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "potentiometer/encoder";
  }

  static const char* value(const ::potentiometer::encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::potentiometer::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 desired\n\
int32 actual\n\
";
  }

  static const char* value(const ::potentiometer::encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::potentiometer::encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desired);
      stream.next(m.actual);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::potentiometer::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::potentiometer::encoder_<ContainerAllocator>& v)
  {
    s << indent << "desired: ";
    Printer<int32_t>::stream(s, indent + "  ", v.desired);
    s << indent << "actual: ";
    Printer<int32_t>::stream(s, indent + "  ", v.actual);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POTENTIOMETER_MESSAGE_ENCODER_H
