// Generated by gencpp from file potentiometer/SendTime.msg
// DO NOT EDIT!


#ifndef POTENTIOMETER_MESSAGE_SENDTIME_H
#define POTENTIOMETER_MESSAGE_SENDTIME_H

#include <ros/service_traits.h>


#include <potentiometer/SendTimeRequest.h>
#include <potentiometer/SendTimeResponse.h>


namespace potentiometer
{

struct SendTime
{

typedef SendTimeRequest Request;
typedef SendTimeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendTime
} // namespace potentiometer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::potentiometer::SendTime > {
  static const char* value()
  {
    return "586a87d88cd92bac79b2ab245f6dd834";
  }

  static const char* value(const ::potentiometer::SendTime&) { return value(); }
};

template<>
struct DataType< ::potentiometer::SendTime > {
  static const char* value()
  {
    return "potentiometer/SendTime";
  }

  static const char* value(const ::potentiometer::SendTime&) { return value(); }
};


// service_traits::MD5Sum< ::potentiometer::SendTimeRequest> should match 
// service_traits::MD5Sum< ::potentiometer::SendTime > 
template<>
struct MD5Sum< ::potentiometer::SendTimeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::potentiometer::SendTime >::value();
  }
  static const char* value(const ::potentiometer::SendTimeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::potentiometer::SendTimeRequest> should match 
// service_traits::DataType< ::potentiometer::SendTime > 
template<>
struct DataType< ::potentiometer::SendTimeRequest>
{
  static const char* value()
  {
    return DataType< ::potentiometer::SendTime >::value();
  }
  static const char* value(const ::potentiometer::SendTimeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::potentiometer::SendTimeResponse> should match 
// service_traits::MD5Sum< ::potentiometer::SendTime > 
template<>
struct MD5Sum< ::potentiometer::SendTimeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::potentiometer::SendTime >::value();
  }
  static const char* value(const ::potentiometer::SendTimeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::potentiometer::SendTimeResponse> should match 
// service_traits::DataType< ::potentiometer::SendTime > 
template<>
struct DataType< ::potentiometer::SendTimeResponse>
{
  static const char* value()
  {
    return DataType< ::potentiometer::SendTime >::value();
  }
  static const char* value(const ::potentiometer::SendTimeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POTENTIOMETER_MESSAGE_SENDTIME_H
