// Generated by gencpp from file potentiometer/SendTimeRequest.msg
// DO NOT EDIT!


#ifndef POTENTIOMETER_MESSAGE_SENDTIMEREQUEST_H
#define POTENTIOMETER_MESSAGE_SENDTIMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace potentiometer
{
template <class ContainerAllocator>
struct SendTimeRequest_
{
  typedef SendTimeRequest_<ContainerAllocator> Type;

  SendTimeRequest_()
    : second(0)
    , nsecond(0)  {
    }
  SendTimeRequest_(const ContainerAllocator& _alloc)
    : second(0)
    , nsecond(0)  {
  (void)_alloc;
    }



   typedef int32_t _second_type;
  _second_type second;

   typedef int32_t _nsecond_type;
  _nsecond_type nsecond;





  typedef boost::shared_ptr< ::potentiometer::SendTimeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::potentiometer::SendTimeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendTimeRequest_

typedef ::potentiometer::SendTimeRequest_<std::allocator<void> > SendTimeRequest;

typedef boost::shared_ptr< ::potentiometer::SendTimeRequest > SendTimeRequestPtr;
typedef boost::shared_ptr< ::potentiometer::SendTimeRequest const> SendTimeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::potentiometer::SendTimeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::potentiometer::SendTimeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace potentiometer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'potentiometer': ['/home/pi/winch_ws/src/potentiometer/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::potentiometer::SendTimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::potentiometer::SendTimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potentiometer::SendTimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potentiometer::SendTimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potentiometer::SendTimeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potentiometer::SendTimeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::potentiometer::SendTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d08210cce4a961455ab53234f5ab98a";
  }

  static const char* value(const ::potentiometer::SendTimeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d08210cce4a9614ULL;
  static const uint64_t static_value2 = 0x55ab53234f5ab98aULL;
};

template<class ContainerAllocator>
struct DataType< ::potentiometer::SendTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "potentiometer/SendTimeRequest";
  }

  static const char* value(const ::potentiometer::SendTimeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::potentiometer::SendTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 second\n\
int32 nsecond\n\
";
  }

  static const char* value(const ::potentiometer::SendTimeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::potentiometer::SendTimeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.second);
      stream.next(m.nsecond);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendTimeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::potentiometer::SendTimeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::potentiometer::SendTimeRequest_<ContainerAllocator>& v)
  {
    s << indent << "second: ";
    Printer<int32_t>::stream(s, indent + "  ", v.second);
    s << indent << "nsecond: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nsecond);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POTENTIOMETER_MESSAGE_SENDTIMEREQUEST_H
