// Generated by gencpp from file system_control/Record.msg
// DO NOT EDIT!


#ifndef SYSTEM_CONTROL_MESSAGE_RECORD_H
#define SYSTEM_CONTROL_MESSAGE_RECORD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_control
{
template <class ContainerAllocator>
struct Record_
{
  typedef Record_<ContainerAllocator> Type;

  Record_()
    : curTime(0.0)
    , curLen(0.0)
    , curDesLen(0.0)  {
    }
  Record_(const ContainerAllocator& _alloc)
    : curTime(0.0)
    , curLen(0.0)
    , curDesLen(0.0)  {
  (void)_alloc;
    }



   typedef double _curTime_type;
  _curTime_type curTime;

   typedef double _curLen_type;
  _curLen_type curLen;

   typedef double _curDesLen_type;
  _curDesLen_type curDesLen;





  typedef boost::shared_ptr< ::system_control::Record_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_control::Record_<ContainerAllocator> const> ConstPtr;

}; // struct Record_

typedef ::system_control::Record_<std::allocator<void> > Record;

typedef boost::shared_ptr< ::system_control::Record > RecordPtr;
typedef boost::shared_ptr< ::system_control::Record const> RecordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_control::Record_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_control::Record_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace system_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'system_control': ['/home/pi/winch_ws/src/system_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::system_control::Record_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_control::Record_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_control::Record_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_control::Record_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_control::Record_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_control::Record_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_control::Record_<ContainerAllocator> >
{
  static const char* value()
  {
    return "735e1749b0f1796a905e67b9dfc3aa99";
  }

  static const char* value(const ::system_control::Record_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x735e1749b0f1796aULL;
  static const uint64_t static_value2 = 0x905e67b9dfc3aa99ULL;
};

template<class ContainerAllocator>
struct DataType< ::system_control::Record_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_control/Record";
  }

  static const char* value(const ::system_control::Record_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_control::Record_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 curTime\n\
float64 curLen\n\
float64 curDesLen\n\
";
  }

  static const char* value(const ::system_control::Record_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_control::Record_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.curTime);
      stream.next(m.curLen);
      stream.next(m.curDesLen);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Record_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_control::Record_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_control::Record_<ContainerAllocator>& v)
  {
    s << indent << "curTime: ";
    Printer<double>::stream(s, indent + "  ", v.curTime);
    s << indent << "curLen: ";
    Printer<double>::stream(s, indent + "  ", v.curLen);
    s << indent << "curDesLen: ";
    Printer<double>::stream(s, indent + "  ", v.curDesLen);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_CONTROL_MESSAGE_RECORD_H
