// Generated by gencpp from file sensor/SendTime.msg
// DO NOT EDIT!


#ifndef SENSOR_MESSAGE_SENDTIME_H
#define SENSOR_MESSAGE_SENDTIME_H

#include <ros/service_traits.h>


#include <sensor/SendTimeRequest.h>
#include <sensor/SendTimeResponse.h>


namespace sensor
{

struct SendTime
{

typedef SendTimeRequest Request;
typedef SendTimeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendTime
} // namespace sensor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor::SendTime > {
  static const char* value()
  {
    return "586a87d88cd92bac79b2ab245f6dd834";
  }

  static const char* value(const ::sensor::SendTime&) { return value(); }
};

template<>
struct DataType< ::sensor::SendTime > {
  static const char* value()
  {
    return "sensor/SendTime";
  }

  static const char* value(const ::sensor::SendTime&) { return value(); }
};


// service_traits::MD5Sum< ::sensor::SendTimeRequest> should match 
// service_traits::MD5Sum< ::sensor::SendTime > 
template<>
struct MD5Sum< ::sensor::SendTimeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor::SendTime >::value();
  }
  static const char* value(const ::sensor::SendTimeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor::SendTimeRequest> should match 
// service_traits::DataType< ::sensor::SendTime > 
template<>
struct DataType< ::sensor::SendTimeRequest>
{
  static const char* value()
  {
    return DataType< ::sensor::SendTime >::value();
  }
  static const char* value(const ::sensor::SendTimeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor::SendTimeResponse> should match 
// service_traits::MD5Sum< ::sensor::SendTime > 
template<>
struct MD5Sum< ::sensor::SendTimeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor::SendTime >::value();
  }
  static const char* value(const ::sensor::SendTimeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor::SendTimeResponse> should match 
// service_traits::DataType< ::sensor::SendTime > 
template<>
struct DataType< ::sensor::SendTimeResponse>
{
  static const char* value()
  {
    return DataType< ::sensor::SendTime >::value();
  }
  static const char* value(const ::sensor::SendTimeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_MESSAGE_SENDTIME_H
